name:                clonger
version:             1.0.0.0
github:              "blueOkiris/clonger"
license:             GPL-3.0
author:              "Dylan Turner"
maintainer:          "dylan.turner@tutanota.com"
copyright:           "2023 Dylan Turner"

extra-source-files:
- README.md

description:         A TUI tool for making naturalistic conlangs all in one place.

dependencies:
- base >= 4.7 && < 5
- brick == 1.4
- text == 1.2.5.0
- vty == 5.37

library:
  source-dirs: src

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  clonger-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clonger

