[package]
name = "clonger"
version = "22.222.1"
edition = "2021"

[[bin]]
name = "clonger"
path = "src/main.rs"

[dependencies]
gtk = { version = "0.15.4", features = [ "v3_24" ] }
libloading = "0.7.3"
